Improve docs to emphasize remark-slug is required
rehypejs/rehype-autolink-headings pull request #12
Opened 2021-07-06 06:55 UTC by lawrencecchen

I was really confused until I saw #4. I don't think the current docs are clear enough. Please consider this fix!

2021-07-06 07:47 UTC, wooorm commented
I dunno, I think this new note is misleading: there are other ways to add IDs (e.g., manually, different tools).

Perhaps the first description can be edited instead, something like:

```diff
-rehype plugin to automatically add links to headings (h1-h6).
+rehype plugin to automatically add links to headings (h1-h6) that already have an ID.
```

2021-07-06 13:22 UTC, ChristianMurphy requested changes

2021-07-06 13:22 UTC, ChristianMurphy commented on readme.md
> +npm install rehype-autolink-headings rehype-slug
```suggestion
npm install rehype-autolink-headings
```

`rehype-slug` is not needed, any method for adding ids to headings could be used.

2021-07-06 13:22 UTC, ChristianMurphy commented on readme.md
> +> **This package will not work without `rehype-slug`. More information under [API](#user-content-api).**
A more accurate version of this is noted in https://github.com/rehypejs/rehype-autolink-headings#rehypeuselink-options

If wanted this note could be moved up higher in the readme.

```suggestion
> Note: this plugin expects `id`s to already exist on headings. One way to add those automatically, is [rehype-slug](https://github.com/rehypejs/rehype-slug) (see example).
```

2021-08-21 07:39 UTC, closed without merging

2021-08-21 07:40 UTC, wooorm commented
I’ve pushed a change that hopefully improves this, but could not merge your PR as there are still unresolved suggestions.